"""empty message

Revision ID: 35de2be97997
Revises: db154c6646d7
Create Date: 2020-07-25 22:12:29.240710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35de2be97997'
down_revision = 'db154c6646d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('breathing', sa.Integer(), nullable=True))
    op.add_column('alarm', sa.Column('decibel_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm', 'decibel_level')
    op.drop_column('alarm', 'breathing')
    # ### end Alembic commands ###
