"""empty message

Revision ID: 4043f57bb2dc
Revises: 
Create Date: 2020-07-21 00:07:33.263488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4043f57bb2dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('baby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('dob_baby', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=True),
    sa.Column('crying', sa.String(length=80), nullable=False),
    sa.Column('overheated', sa.Boolean(), nullable=False),
    sa.Column('breathing', sa.Boolean(), nullable=False),
    sa.Column('face_down', sa.Boolean(), nullable=False),
    sa.Column('out_of_crib', sa.Boolean(), nullable=False),
    sa.Column('time_stamp', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['baby.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=True),
    sa.Column('face_direction', sa.String(length=10), nullable=False),
    sa.Column('breathing', sa.String(length=10), nullable=False),
    sa.Column('last_movement', sa.String(length=10), nullable=False),
    sa.Column('time_stamp', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['baby.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    op.drop_table('alarm')
    op.drop_table('baby')
    op.drop_table('user')
    # ### end Alembic commands ###
