"""empty message

Revision ID: 4342234e441a
Revises: 4043f57bb2dc
Create Date: 2020-07-21 00:25:59.406941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4342234e441a'
down_revision = '4043f57bb2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=160), nullable=True))
    op.create_unique_constraint(None, 'user', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
