"""empty message

Revision ID: 481de2ee43c0
Revises: 6906a3d33095
Create Date: 2020-07-21 21:51:17.894643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481de2ee43c0'
down_revision = '6906a3d33095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baby', sa.Column('baby_gender', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baby', 'baby_gender')
    # ### end Alembic commands ###
