"""empty message

Revision ID: 4d6cdda88ff7
Revises: 481de2ee43c0
Create Date: 2020-07-21 23:43:45.898577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d6cdda88ff7'
down_revision = '481de2ee43c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baby', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint('baby_ibfk_1', 'baby', type_='foreignkey')
    op.create_foreign_key(None, 'baby', 'user', ['parent_id'], ['id'])
    op.drop_column('baby', 'baby_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baby', sa.Column('baby_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'baby', type_='foreignkey')
    op.create_foreign_key('baby_ibfk_1', 'baby', 'user', ['baby_id'], ['id'])
    op.drop_column('baby', 'parent_id')
    # ### end Alembic commands ###
