"""empty message

Revision ID: 56cbe4f3969d
Revises: 4342234e441a
Create Date: 2020-07-21 00:29:19.784412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56cbe4f3969d'
down_revision = '4342234e441a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('jwt', sa.String(length=160), nullable=True))
    op.drop_index('token', table_name='user')
    op.create_unique_constraint(None, 'user', ['jwt'])
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', mysql.VARCHAR(length=160), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('token', 'user', ['token'], unique=True)
    op.drop_column('user', 'jwt')
    # ### end Alembic commands ###
