"""empty message

Revision ID: 633e23f747b3
Revises: b6a154621216
Create Date: 2020-07-25 22:11:29.176185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '633e23f747b3'
down_revision = 'b6a154621216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm', 'tmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('tmp', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
