"""empty message

Revision ID: 6906a3d33095
Revises: 280a955157eb
Create Date: 2020-07-21 21:49:37.589405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6906a3d33095'
down_revision = '280a955157eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baby', sa.Column('time_zone', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baby', 'time_zone')
    # ### end Alembic commands ###
