"""empty message

Revision ID: 7efa4e875494
Revises: daa622a8989c
Create Date: 2020-07-23 18:26:19.734518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7efa4e875494'
down_revision = 'daa622a8989c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm', 'time_stamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('time_stamp', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
