"""empty message

Revision ID: b6a154621216
Revises: 3ae035c82060
Create Date: 2020-07-25 22:10:36.884217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a154621216'
down_revision = '3ae035c82060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('tmp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm', 'tmp')
    # ### end Alembic commands ###
