"""empty message

Revision ID: db154c6646d7
Revises: 633e23f747b3
Create Date: 2020-07-25 22:12:02.176942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db154c6646d7'
down_revision = '633e23f747b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm', 'breathing')
    op.drop_column('alarm', 'decibel_level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('decibel_level', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('breathing', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
