"""empty message

Revision ID: dbf53ba6fa63
Revises: 35de2be97997
Create Date: 2020-07-27 04:10:38.339056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf53ba6fa63'
down_revision = '35de2be97997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('bored', sa.Integer(), nullable=True))
    op.add_column('alarm', sa.Column('colic', sa.Integer(), nullable=True))
    op.add_column('alarm', sa.Column('enough', sa.Integer(), nullable=True))
    op.add_column('alarm', sa.Column('hungry', sa.Integer(), nullable=True))
    op.add_column('alarm', sa.Column('sick', sa.Integer(), nullable=True))
    op.add_column('alarm', sa.Column('tired', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm', 'tired')
    op.drop_column('alarm', 'sick')
    op.drop_column('alarm', 'hungry')
    op.drop_column('alarm', 'enough')
    op.drop_column('alarm', 'colic')
    op.drop_column('alarm', 'bored')
    # ### end Alembic commands ###
